# pnpm-workspace.yaml
packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  "@clerk/shared": true
  "@prisma/engines": false
  esbuild: false
  msgpackr-extract: false
  msw: false
  prisma: false
  sharp: false
  unrs-resolver: false
